const SCRY_DIR = "scry";
const REPORT_DIR = "scry/report";
const TRACE_RESULT_FILE_NAME = "TraceResult";
const TRACE_RESULT_FILE_EXTENSION = "html";
const REPORT_FILE_DATE_FORMAT = "YYYY-MM-DD_HH-mm-ss";
const BLOB_TYPE = "text/html";

export {
  SCRY_DIR,
  REPORT_DIR,
  TRACE_RESULT_FILE_NAME,
  TRACE_RESULT_FILE_EXTENSION,
  REPORT_FILE_DATE_FORMAT,
  BLOB_TYPE,
};
